def calculations():
    radius1 = input("Enter the radius: ")
    radius1 = float(radius1)
    print("Circle: r = ",radius1, ", area = ", 3.14159*radius1**2, sep="")
    radius2 = input("Enter the radius: ")
    radius2 = float(radius2)
    print("Sphere: r = ",radius2, ", volume = ", (4/3)*3.14159*radius2**3, sep="")
    height1 = input("Enter the height: ")
    height1 = float(height1)
    width = input("Enter the width: ")
    width = float(width)
    print("Rectangle: height = ",height1, ", width = ", width, ", area = ", height1 * width, sep="")
    side_length1 = input("Enter the side length: ")
    side_length1 = float(side_length1)
    print("Square: side length = ", side_length1, ",  area = ", side_length1**2, sep="")
    leg_length = input("Enter the leg length: ")
    leg_length = float(leg_length)
    height2 = input("Enter the height: ")
    height2 = float(height2)
    print("Isosceles Triangle: side = ", leg_length, ", height = ", height2, ", area = ", (1/2)*leg_length*height2, sep="")
    side_length2 = input("Enter the side length: ")
    side_length2 = float(side_length2)
    print("Equilateral Triangle: side = ", side_length2, ", area = ", (3**(1/2)/4)*(side_length2**2), sep="")
    base1 = input("Enter base 1: ")
    base1 = float(base1)
    base2 = input("Enter base 2: ")
    base2 = float(base2)
    height3 = input("Enter height: ")
    height3 = float(height3)
    print("Trapezoid: base 1 = ", base1, ", base 2 = ", base2, ", height = ", height3, ", area = ", (base1+base2)/2 * height3, sep="")

def main():
    calculations()

main()